### ISSUE TITLE
Include screenshot in the README?

### ISSUE THREAD

**Issue by KM4YRI** [tucnak/novile#9]
Would it be possible to include a screenshot of the text editor somewhere?  Being that I'm still waiting on Qt to call me back before they'll even send me a download link, I'm just really curious as to how this project compares to QScintilla2 (I'm really hopeful that it blows it away).   

Could you commit a screenshot to the repo?  And possibly add a link to the readme (or better yet, rename the readme to README.md and use github-markdown to display it in the github view).

**Comment by tucnak** [comment]
Hey,

I can't make one at the moment unfortunately, but look here: https://ace.c9.io/

Novile is basically Ace.js over QtWebKit. It will most definitely blow qscintilla2 away (at least judging by the looks and of basic API), but you really should consider whether you want to use novile or not because of its biggest dependency — QtWebKit, which is pretty darn heavy... I can't really justify utilizing a library as heavy as QtWebKit for something like a code editor, but here I am, trying to maintain a code editor library depending on QtWebKit.

**Comment by KM4YRI** [comment]
OK, that makes sense.  I wasn't sure if it was a direct drop-in or if it was modified.  I'll go ahead and close the issue, as I agree it's not really needed if it's basically just the Ace editor in a Qt window.

I've not used QtWebKit but I can't imagine it being worse than a Chrome tab.  Scintilla just seems really clunky and old.  But at the same time I'm a bit shocked over the number of bugs open for the Ace editor, the lack of syntax highlighting for Python, and bits of the syntax highlighting not implemented.  It sounds like I really need to try the Ace editor out before I commit to Ace or Novile.  Seems great otherwise though.  Anyway I'm rambling at this point.  Thanks for the help, I'm closing the issue now.
